use crate::engine::{auto_outline_svg, parse_join_style, preview_svg, run_pack, Params};
use wasm_bindgen::prelude::*;

/// Standalone SVG of one clipped sticker (art masked to the border), for a live preview.
#[wasm_bindgen]
pub fn preview(border_svg: String, image_bytes: Vec<u8>, image_ext: String) -> Result<String, JsValue> {
    preview_svg(&border_svg, &image_bytes, &image_ext).map_err(|e| JsValue::from_str(&e))
}

/// Outline SVG generated by dilating a traced art silhouette (viewBox-unit x,y pairs). `style`
/// is external|all|sharp. Usable directly as the border.
#[wasm_bindgen]
pub fn auto_outline(
    points: Vec<f64>,
    lengths: Vec<u32>,
    vb_min_x: f64,
    vb_min_y: f64,
    vb_w: f64,
    vb_h: f64,
    margin: f64,
    round_radius: f64,
    style: String,
    stroke: f64,
) -> Result<String, JsValue> {
    let js = parse_join_style(&style).map_err(|e| JsValue::from_str(&e))?;
    auto_outline_svg(&points, &lengths, &[vb_min_x, vb_min_y, vb_w, vb_h], margin, round_radius, js, stroke).map_err(|e| JsValue::from_str(&e))
}

#[wasm_bindgen]
pub struct PackResult {
    count: usize,
    content_svg: String,
    outline_svg: String,
    content_pdf: Vec<u8>,
    outline_pdf: Vec<u8>,
}

#[wasm_bindgen]
impl PackResult {
    #[wasm_bindgen(getter)]
    pub fn count(&self) -> usize {
        self.count
    }
    #[wasm_bindgen(getter)]
    pub fn content_svg(&self) -> String {
        self.content_svg.clone()
    }
    #[wasm_bindgen(getter)]
    pub fn outline_svg(&self) -> String {
        self.outline_svg.clone()
    }
    #[wasm_bindgen(getter)]
    pub fn content_pdf(&self) -> Vec<u8> {
        self.content_pdf.clone()
    }
    #[wasm_bindgen(getter)]
    pub fn outline_pdf(&self) -> Vec<u8> {
        self.outline_pdf.clone()
    }
}

/// Run the full pack. `image_bytes` empty + `image_ext` "" => single-SVG mode (border is art).
/// `sticker_width <= 0` => none; `max_count < 0` => none.
#[allow(clippy::too_many_arguments)]
#[wasm_bindgen]
pub fn pack(
    border_svg: String,
    image_bytes: Vec<u8>,
    image_ext: String,
    sticker_width: f64,
    page_w: f64,
    page_h: f64,
    margin: f64,
    spacing: f64,
    method: String,
    rotations: u32,
    max_count: i32,
    simplify: f64,
    greedy_attempts: u32,
    stroke: f64,
    want_pdf: bool,
    pdf_background: bool,
    reg_marks: bool,
    reg_draw: bool,
    reg_length_in: f64,
    reg_thickness_in: f64,
    reg_inset_l_in: f64,
    reg_inset_t_in: f64,
    reg_inset_r_in: f64,
    reg_inset_b_in: f64,
    on_progress: js_sys::Function,
) -> Result<PackResult, JsValue> {
    let p = Params {
        sticker_width: (sticker_width > 0.0).then_some(sticker_width),
        page_w,
        page_h,
        margin,
        spacing,
        method,
        rotations: rotations as usize,
        landscape: false,
        max_count: (max_count >= 0).then_some(max_count as usize),
        simplify,
        greedy_attempts: greedy_attempts as usize,
        stroke,
        want_pdf,
        pdf_background,
        reg_marks,
        reg_draw,
        reg_length_in,
        reg_thickness_in,
        reg_inset_l_in,
        reg_inset_t_in,
        reg_inset_r_in,
        reg_inset_b_in,
    };
    let progress = |stage: &str, frac: f64| {
        let _ = on_progress.call2(&JsValue::NULL, &JsValue::from_str(stage), &JsValue::from_f64(frac));
    };
    let out = run_pack(&border_svg, &image_bytes, &image_ext, &p, &progress).map_err(|e| JsValue::from_str(&e))?;
    Ok(PackResult {
        count: out.count,
        content_svg: out.content_svg,
        outline_svg: out.outline_svg,
        content_pdf: out.content_pdf,
        outline_pdf: out.outline_pdf,
    })
}
